In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import os

In [9]:
proj_dir = os.path.join(Path.home(), 'Documents', 'WorkSpace', 'corpus-comparison')
analysis_dir = os.path.join(proj_dir, 'analysis')
corpora_dir = os.path.join(proj_dir, 'corpora')

print(f"Project directory: {proj_dir}")
print(f"Analysis directory: {analysis_dir}")
print(f"Corpora directory: {corpora_dir}")

Project directory: /Users/bagjuhyeon/Documents/WorkSpace/corpus-comparison
Analysis directory: /Users/bagjuhyeon/Documents/WorkSpace/corpus-comparison/analysis
Corpora directory: /Users/bagjuhyeon/Documents/WorkSpace/corpus-comparison/corpora

# File-processing

## convert csv -> xlsx

In [61]:
ELP_LDT_data_path = os.path.join(corpora_dir, 'behavior-exp', 'ELP-LDT.csv')

if os.path.exists(ELP_LDT_data_path):
    df = pd.read_csv(ELP_LDT_data_path)
    df.to_excel(os.path.join(corpora_dir, 'behavior-exp', 'ELP-LDT.xlsx'), index=False)
    print("Conversion complete: word_stimuli.csv -> word_stimuli.xlsx")
else:
    raise FileNotFoundError(f"File not found: {ELP_LDT_data_path}")

Conversion complete: word_stimuli.csv -> word_stimuli.xlsx

In [86]:
ELP_LDT_data = pd.read_excel(os.path.join(corpora_dir, 'behavior-exp', 'ELP-LDT.xlsx'))
ELP_LDT_data

,Word,Length,Freq_HAL,Log_Freq_HAL,SUBTLWF,I_Mean_RT,I_Zscore,I_SD,Obs,I_Mean_Accuracy
0,a,1,"10,610,626",16.177,"20,415.270",798.917,-0.013,333.849,24,0.73
1,aah,3,222,5.403,52.710,816.429,0.214,186.029,21,0.62
2,Aaron,5,"10,806",9.288,14.650,736.062,-0.111,289.010,32,0.97
3,aback,5,387,5.958,0.290,796.267,0.110,171.607,15,0.45
4,abacus,6,513,6.240,0.240,964.400,0.655,488.996,15,0.47
...,...,...,...,...,...,...,...,...,...,...
40476,zoom,4,"4,920",8.501,3.550,549.758,-0.762,97.649,33,1.00
40477,zooming,7,523,6.260,0.630,709.690,-0.293,283.106,29,0.88
40478,zooms,5,385,5.953,0.060,666.933,-0.476,232.109,30,0.94
40479,zucchini,8,314,5.749,0.960,848.679,0.239,259.819,28,0.85
40480,Zurich,6,"1,770",7.479,2.430,763.000,0.091,184.257,21,0.64

remove HAL related columm

In [87]:
ELP_LDT_data.drop(columns=['Freq_HAL', 'Log_Freq_HAL'], inplace=True)
ELP_LDT_data

,Word,Length,SUBTLWF,I_Mean_RT,I_Zscore,I_SD,Obs,I_Mean_Accuracy
0,a,1,"20,415.270",798.917,-0.013,333.849,24,0.73
1,aah,3,52.710,816.429,0.214,186.029,21,0.62
2,Aaron,5,14.650,736.062,-0.111,289.010,32,0.97
3,aback,5,0.290,796.267,0.110,171.607,15,0.45
4,abacus,6,0.240,964.400,0.655,488.996,15,0.47
...,...,...,...,...,...,...,...,...
40476,zoom,4,3.550,549.758,-0.762,97.649,33,1.00
40477,zooming,7,0.630,709.690,-0.293,283.106,29,0.88
40478,zooms,5,0.060,666.933,-0.476,232.109,30,0.94
40479,zucchini,8,0.960,848.679,0.239,259.819,28,0.85
40480,Zurich,6,2.430,763.000,0.091,184.257,21,0.64

keep only row which have the SUBTLWF

In [88]:
# as we can see, if the nan value is not processed as the none or nan -> therefore, we need to find and specify them.
ELP_LDT_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40481 entries, 0 to 40480
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Word             40480 non-null  object
 1   Length           40481 non-null  int64
 2   SUBTLWF          40481 non-null  object
 3   I_Mean_RT        40481 non-null  object
 4   I_Zscore         40481 non-null  object
 5   I_SD             40481 non-null  object
 6   Obs              40481 non-null  object
 7   I_Mean_Accuracy  40481 non-null  float64
dtypes: float64(1), int64(1), object(6)
memory usage: 2.5+ MB

In [89]:
# also, need to erase the comma ex) 20,415.270 -> 20415.270
ELP_LDT_data['SUBTLWF'].unique()

array(['20,415.270', '52.710', '14.650', ..., '434.330', '29.000',
       '16.820'], shape=(2990,), dtype=object)

In [90]:
# remove comma for all exist columns
ELP_LDT_data['SUBTLWF'] = ELP_LDT_data['SUBTLWF'].str.replace(',', '')
ELP_LDT_data['I_Mean_RT'] = ELP_LDT_data['I_Mean_RT'].str.replace(',', '')
ELP_LDT_data['I_Zscore'] = ELP_LDT_data['I_Zscore'].str.replace(',', '')
ELP_LDT_data['I_SD'] = ELP_LDT_data['I_SD'].str.replace(',', '')
ELP_LDT_data['Obs'] = ELP_LDT_data['Obs'].str.replace(',', '')
ELP_LDT_data.head()

     Word  Length    SUBTLWF I_Mean_RT I_Zscore     I_SD Obs  I_Mean_Accuracy
0       a       1  20415.270   798.917   -0.013  333.849  24             0.73
1     aah       3     52.710   816.429    0.214  186.029  21             0.62
2   Aaron       5     14.650   736.062   -0.111  289.010  32             0.97
3   aback       5      0.290   796.267    0.110  171.607  15             0.45
4  abacus       6      0.240   964.400    0.655  488.996  15             0.47

In [91]:
# float으로 바로 변환이 안 되는데, 이는 '#' 때문.
ELP_LDT_data['SUBTLWF'].astype('float')

ValueError: could not convert string to float: '#'

In [92]:
# 아래의 값들이 drop 대상.
ELP_LDT_data[ELP_LDT_data['SUBTLWF'] == '#']

,Word,Length,SUBTLWF,I_Mean_RT,I_Zscore,I_SD,Obs,I_Mean_Accuracy
10,abasement,9,#,1037.059,0.923,311.845,17,0.53
11,abash,5,#,748.714,0.229,194.366,21,0.68
26,Abe,3,#,820.667,0.075,254.987,33,1.00
29,Abel's,6,#,840.143,0.196,333.080,28,0.82
83,abridgment,10,#,1152.611,0.873,484.354,18,0.60
...,...,...,...,...,...,...,...,...
40415,young's,7,#,844.483,0.038,435.469,29,0.91
40418,youngster's,11,#,763.156,-0.125,260.448,32,0.97
40420,you're,6,#,679.091,-0.288,174.945,33,1.00
40427,you've,6,#,725.903,-0.352,255.048,31,0.91
40429,Yucatan,7,#,813.542,0.310,237.189,24,0.73

In [ ]:
# drop any row which has '#' in the columns_to_check
columns_to_check = ELP_LDT_data.columns.drop(['Word', 'Length', 'I_Mean_Accuracy'])
mask = (ELP_LDT_data[columns_to_check].isin(['#'])).any(axis=1)
ELP_LDT_data = ELP_LDT_data[~mask].reset_index(drop=True)
ELP_LDT_data

,Word,Length,SUBTLWF,I_Mean_RT,I_Zscore,I_SD,Obs,I_Mean_Accuracy
0,a,1,20415.270,798.917,-0.013,333.849,24,0.73
1,aah,3,52.710,816.429,0.214,186.029,21,0.62
2,Aaron,5,14.650,736.062,-0.111,289.010,32,0.97
3,aback,5,0.290,796.267,0.110,171.607,15,0.45
4,abacus,6,0.240,964.400,0.655,488.996,15,0.47
...,...,...,...,...,...,...,...,...
35495,zoom,4,3.550,549.758,-0.762,97.649,33,1.00
35496,zooming,7,0.630,709.690,-0.293,283.106,29,0.88
35497,zooms,5,0.060,666.933,-0.476,232.109,30,0.94
35498,zucchini,8,0.960,848.679,0.239,259.819,28,0.85
35499,Zurich,6,2.430,763.000,0.091,184.257,21,0.64

In [94]:
# change columns dtype
ELP_LDT_data['SUBTLWF'] = ELP_LDT_data['SUBTLWF'].astype('float')
ELP_LDT_data['I_Mean_RT'] = ELP_LDT_data['I_Mean_RT'].astype('float')
ELP_LDT_data['I_Zscore'] = ELP_LDT_data['I_Zscore'].astype('float')
ELP_LDT_data['I_SD'] = ELP_LDT_data['I_SD'].astype('float')
ELP_LDT_data['Obs'] = ELP_LDT_data['Obs'].astype('float')

In [100]:
# applying lower to Word 
ELP_LDT_data['Word'] = ELP_LDT_data['Word'].str.lower()

In [101]:
ELP_LDT_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35500 entries, 0 to 35499
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Word             35499 non-null  object
 1   Length           35500 non-null  int64
 2   SUBTLWF          35500 non-null  float64
 3   I_Mean_RT        35500 non-null  float64
 4   I_Zscore         35500 non-null  float64
 5   I_SD             35500 non-null  float64
 6   Obs              35500 non-null  float64
 7   I_Mean_Accuracy  35500 non-null  float64
dtypes: float64(6), int64(1), object(1)
memory usage: 2.2+ MB

In [96]:
ELP_LDT_data.to_excel(os.path.join(corpora_dir, 'behavior-exp', 'ELP-LDT(preprocessed).xlsx'), index=False)

# Merging with KE corpora(depreted): already exist in data files.

In [102]:
KE_E_Lex_path = os.path.join(corpora_dir, 'merged_corpora', 'CSAT_E_final.xlsx')
KE_E_Lex = pd.read_excel(KE_E_Lex_path)
ELP_LDT_path = os.path.join(corpora_dir, 'behavior-exp', 'ELP-LDT(preprocessed).xlsx')
ELP_LDT_data = pd.read_excel(ELP_LDT_path)
KE_E_Lex.head()

,Word,Length,CSAT_Freq,CSAT_only_Freq,Textbook_only_Freq,Freq_HAL,SUBTLWF,Freq_KF,CSAT_RFreq,CSAT_only_RFreq,...,Emotional_Valence,Emotional_Arousal,Emotional_Dominance,I_Mean_RT,I_Zscore,I_SD,I_NMG_Mean_RT,I_NMG_Zscore,I_NMG_SD,POS
0,a,1,17505.0,9773.0,7732.0,10610626,1041178.77,23237.0,24675.191037,23843.796660,...,NaN,NaN,NaN,798.917,-0.013,333.849,662.087,-0.323,174.691,minor|NN
1,aah,3,NaN,NaN,NaN,222,2688.21,1.0,NaN,NaN,...,NaN,NaN,NaN,816.429,0.214,186.029,646.400,-0.349,130.445,NaN
2,aaron,5,7.0,1.0,6.0,10806,747.15,7.0,9.867257,2.439762,...,NaN,NaN,NaN,736.062,-0.111,289.010,686.111,-0.203,179.290,NN
3,aback,5,NaN,NaN,NaN,387,14.79,2.0,NaN,NaN,...,NaN,NaN,NaN,796.267,0.110,171.607,596.538,-0.550,89.453,RB
4,abacus,6,NaN,NaN,NaN,513,12.24,NaN,NaN,NaN,...,NaN,NaN,NaN,964.400,0.655,488.996,792.688,0.309,200.186,NN

In [ ]:
# filter the KE words
mask = ~KE_E_Lex['CSAT_Freq'].isna()
KE = KE_E_Lex[mask].reset_index(drop=True)
KE

,Word,Length,CSAT_Freq,CSAT_only_Freq,Textbook_only_Freq,Freq_HAL,SUBTLWF,Freq_KF,CSAT_RFreq,CSAT_only_RFreq,...,Emotional_Valence,Emotional_Arousal,Emotional_Dominance,I_Mean_RT,I_Zscore,I_SD,I_NMG_Mean_RT,I_NMG_Zscore,I_NMG_SD,POS
0,a,1,17505.0,9773.0,7732.0,10610626,1041178.77,23237.0,24675.191037,23843.796660,...,NaN,NaN,NaN,798.917,-0.013,333.849,662.087,-0.323,174.691,minor|NN
1,aaron,5,7.0,1.0,6.0,10806,747.15,7.0,9.867257,2.439762,...,NaN,NaN,NaN,736.062,-0.111,289.010,686.111,-0.203,179.290,NN
2,abandon,7,7.0,5.0,2.0,3761,413.10,17.0,9.867257,12.198811,...,2.84,3.73,3.32,695.719,-0.312,220.412,623.963,-0.516,98.251,VB|NN
3,abandoned,9,12.0,5.0,7.0,5160,677.79,25.0,16.915298,12.198811,...,NaN,NaN,NaN,860.774,-0.095,447.558,635.160,-0.487,101.648,VB|JJ
4,abandoning,10,3.0,3.0,NaN,1005,86.19,7.0,4.228825,7.319287,...,NaN,NaN,NaN,740.545,-0.111,288.435,782.783,0.064,218.574,VB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16349,zombies,7,3.0,NaN,3.0,2588,114.75,1.0,4.228825,NaN,...,NaN,NaN,NaN,737.562,-0.148,197.720,645.259,-0.333,92.958,NN
16350,zone,4,19.0,6.0,13.0,17300,1026.12,11.0,26.782555,14.638574,...,4.75,3.78,5.23,577.727,-0.771,165.732,615.357,-0.498,93.202,NN
16351,zones,5,17.0,8.0,9.0,3388,89.76,3.0,23.963339,19.518098,...,NaN,NaN,NaN,605.229,-0.673,153.891,590.080,-0.580,96.943,NN
16352,zoo,3,31.0,21.0,10.0,4317,696.15,9.0,43.697853,51.235008,...,7.00,5.63,6.33,572.562,-0.793,180.819,662.571,-0.198,109.818,NN
16353,zoologist,9,2.0,2.0,NaN,301,12.24,2.0,2.819216,4.879525,...,NaN,NaN,NaN,714.088,-0.118,165.017,732.696,0.190,162.795,NN

# reduce file

In [112]:
KE_E_Lex_path = os.path.join(corpora_dir, 'merged_corpora', 'CSAT_E_final.xlsx')
KE_E_Lex = pd.read_excel(KE_E_Lex_path)
ELP_LDT_path = os.path.join(corpora_dir, 'behavior-exp', 'ELP-LDT(preprocessed).xlsx')
ELP_LDT_data = pd.read_excel(ELP_LDT_path)
KE_E_Lex.columns, ELP_LDT_data.columns

(Index(['Word', 'Length', 'CSAT_Freq', 'CSAT_only_Freq', 'Textbook_only_Freq',
        'Freq_HAL', 'SUBTLWF', 'Freq_KF', 'CSAT_RFreq', 'CSAT_only_RFreq',
        'Textbook_only_RFreq', 'RFreq_HAL', 'SUBTLRWF', 'RFreq_KF',
        'Ortho_N_CSAT', 'Ortho_N_CSAT(only)', 'Ortho_N_Textbook(only)',
        'Ortho_N', 'OLD20_CSAT', 'OLD20_CSAT(only)', 'OLD20_Textbook(only)',
        'OLD', 'SUBTLCD', 'Concreteness_Rating', 'Age_Of_Acquisition',
        'Emotional_Valence', 'Emotional_Arousal', 'Emotional_Dominance',
        'I_Mean_RT', 'I_Zscore', 'I_SD', 'I_NMG_Mean_RT', 'I_NMG_Zscore',
        'I_NMG_SD', 'POS'],
       dtype='object'),
 Index(['Word', 'Length', 'SUBTLWF', 'I_Mean_RT', 'I_Zscore', 'I_SD', 'Obs',
        'I_Mean_Accuracy'],
       dtype='object'))

## attach the additional data

In [ ]:
# ELP_LDT_data[['Word', 'Obs', 'I_Mean_Accuracy']]
ELP_LDT_data = pd.merge(KE_E_Lex, ELP_LDT_data[['Word', 'Obs', 'I_Mean_Accuracy']], on='Word', how='left')
ELP_LDT_data

,Word,Length,CSAT_Freq,CSAT_only_Freq,Textbook_only_Freq,Freq_HAL,SUBTLWF,Freq_KF,CSAT_RFreq,CSAT_only_RFreq,...,Emotional_Dominance,I_Mean_RT,I_Zscore,I_SD,I_NMG_Mean_RT,I_NMG_Zscore,I_NMG_SD,POS,Obs,I_Mean_Accuracy
0,a,1,17505.0,9773.0,7732.0,10610626,1041178.77,23237.0,24675.191037,23843.796660,...,NaN,798.917,-0.013,333.849,662.087,-0.323,174.691,minor|NN,24.0,0.73
1,aah,3,NaN,NaN,NaN,222,2688.21,1.0,NaN,NaN,...,NaN,816.429,0.214,186.029,646.400,-0.349,130.445,NaN,21.0,0.62
2,aaron,5,7.0,1.0,6.0,10806,747.15,7.0,9.867257,2.439762,...,NaN,736.062,-0.111,289.010,686.111,-0.203,179.290,NN,NaN,NaN
3,aback,5,NaN,NaN,NaN,387,14.79,2.0,NaN,NaN,...,NaN,796.267,0.110,171.607,596.538,-0.550,89.453,RB,15.0,0.45
4,abacus,6,NaN,NaN,NaN,513,12.24,NaN,NaN,NaN,...,NaN,964.400,0.655,488.996,792.688,0.309,200.186,NN,15.0,0.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40476,zooming,7,NaN,NaN,NaN,523,32.13,1.0,NaN,NaN,...,NaN,709.690,-0.293,283.106,672.370,-0.218,92.353,VB,29.0,0.88
40477,zooms,5,NaN,NaN,NaN,385,3.06,1.0,NaN,NaN,...,NaN,666.933,-0.476,232.109,613.833,-0.552,88.295,VB,30.0,0.94
40478,zucchini,8,NaN,NaN,NaN,314,48.96,NaN,NaN,NaN,...,6.19,848.679,0.239,259.819,756.000,0.207,209.064,NN,28.0,0.85
40479,zurich,6,NaN,NaN,NaN,1770,123.93,2.0,NaN,NaN,...,NaN,763.000,0.091,184.257,822.640,0.213,221.482,NN,NaN,NaN
40480,NaN,4,NaN,NaN,NaN,15410,27.03,13.0,NaN,NaN,...,NaN,703.467,-0.278,168.922,595.741,-0.562,86.852,NN|JJ,30.0,0.88

In [120]:
behavior_cols = ['Word', 'Length', 'CSAT_Freq', 'SUBTLWF', 
                'I_Mean_RT', 'I_Zscore', 'I_SD', 'Obs', 'I_Mean_Accuracy']
ELP_LDT_data = ELP_LDT_data[behavior_cols]
ELP_LDT_data

,Word,Length,CSAT_Freq,SUBTLWF,I_Mean_RT,I_Zscore,I_SD,Obs,I_Mean_Accuracy
0,a,1,17505.0,1041178.77,798.917,-0.013,333.849,24.0,0.73
1,aah,3,NaN,2688.21,816.429,0.214,186.029,21.0,0.62
2,aaron,5,7.0,747.15,736.062,-0.111,289.010,NaN,NaN
3,aback,5,NaN,14.79,796.267,0.110,171.607,15.0,0.45
4,abacus,6,NaN,12.24,964.400,0.655,488.996,15.0,0.47
...,...,...,...,...,...,...,...,...,...
40476,zooming,7,NaN,32.13,709.690,-0.293,283.106,29.0,0.88
40477,zooms,5,NaN,3.06,666.933,-0.476,232.109,30.0,0.94
40478,zucchini,8,NaN,48.96,848.679,0.239,259.819,28.0,0.85
40479,zurich,6,NaN,123.93,763.000,0.091,184.257,NaN,NaN
40480,NaN,4,NaN,27.03,703.467,-0.278,168.922,30.0,0.88

In [132]:
mask = ELP_LDT_data[['CSAT_Freq', 'SUBTLWF', 'I_Mean_RT', 'I_Zscore', 'I_SD', 'I_Mean_Accuracy']].isna().any(axis=1)
ELP_LDT_data = ELP_LDT_data[~mask].reset_index(drop=True)
ELP_LDT_data

,Word,Length,CSAT_Freq,SUBTLWF,I_Mean_RT,I_Zscore,I_SD,Obs,I_Mean_Accuracy
0,a,1,17505.0,1041178.77,798.917,-0.013,333.849,24.0,0.73
1,abandon,7,7.0,413.10,695.719,-0.312,220.412,32.0,0.97
2,abandoned,9,12.0,677.79,860.774,-0.095,447.558,31.0,0.91
3,abandoning,10,3.0,86.19,740.545,-0.111,288.435,33.0,1.00
4,abandonment,11,2.0,48.96,771.088,-0.002,229.526,34.0,1.00
...,...,...,...,...,...,...,...,...,...
15212,zombies,7,3.0,114.75,737.562,-0.148,197.720,32.0,1.00
15213,zone,4,19.0,1026.12,577.727,-0.771,165.732,33.0,1.00
15214,zones,5,17.0,89.76,605.229,-0.673,153.891,35.0,1.00
15215,zoo,3,31.0,696.15,572.562,-0.793,180.819,32.0,0.97
15216,zoologist,9,2.0,12.24,714.088,-0.118,165.017,34.0,1.00