# Corpus 전처리

현재 데이터는 xlsx로 저장이 되어 있다. <br/><br/>COCA 코퍼스와 같은 영어 corpus와 비교 예정이기에 전처리가 필요한데, 이를 위해 데이터 저장 포멧은 크게 3가지가 있고 아래와 같다. <br/> <br/> <br/> 1. csv: 엑셀로 읽을 수 있으며 가독성이 좋다. 테이블 형식의 데이터 정리에 유용. <br/> 2. parquet: 하둡과 같은 프레임 워크를 위해 개발된 데이터 압축 형태이고, 압축이 가장 잘되는 열 방향 데이터 정보 포멧. <br/> 3. json: 일반적으로 CS 분야에서 통신이나 테이블 형태가 아닌 데이터 저장에 많이 사용되는 형태. 압축률이 좋지는 않으나 유연한 구조로 인해 확장이 쉽다.<br/><br/> <br/> 고로 이번에는 json으로 사용하려고 한다.

## 개발 환경 세팅

python을 언어로 사용할 거고, uv를 사용해 필요한 라이브러리를 다운로드할 것이다. 
<br/> uv 란? -> python 라이브러리를 굉장히 빨리 다운로드해주는 pkg-manager
<br/> 혹시라도 읽고 계신 분이 CS 분야 전공자라면, 부디 쓰시길 바랍니다. conda, pip 대비 비교도 안될 정도로 빠릅니다,,

만약 github에서 pull하고 사용 중이라면 pyproject.toml 파일을 열어보면 dependencies에서 라이브러리 이름을 확인할 수 있을 텐데 그게 꼭 설치되어야 아래가 진행 가능하다!!!

## 데이터 전처리 전략 및 순서

전처리 순서는 아래와 같다.<br/><br/><br/> 1. 문잔 단위 분할 <br/> 2. 단어 단위 분할 및 품사 태깅

### 문장 기준 분할

수능 영어 듣기 corpus: csat_listening_article

### 라이브러리 import

In [1]:
import nltk # Natural Language Toolkit
from nltk import word_tokenize, pos_tag, sent_tokenize # Natural Language Toolkit
from nltk.tokenize import WhitespaceTokenizer
#import contractions # 영어 줄임말 풀기 -> 축약형은 풀지 않기로,,
import pandas as pd # 데이터 처리
import numpy as np # 데이터 처리
import seaborn as sns # 데이터 시각화
from tqdm import tqdm # 데이터 처리
import re # 정규식으로 특수기호 및 char 처리
import json # 데이터 가공 후 저장할 형식
from typing import Any, Dict, List  # python data-type 정의
from pathlib import Path # 파일 경로 처리
import os # 파일 경로 및 처리
from sklearn.preprocessing import StandardScaler # 전처리 시 normalize
from customTokenizer import CustomTokenizer
from preprocessor import Preprocessor, TargetCorpusPreprocessor
from json_handler import JsonFileHandler

In [2]:
# 사용 예시
def test_configurable_tokenizer():

    # 축약형과 소유격 보존 + 토큰 필터링
    tokenizer = CustomTokenizer(
        preserve_contractions=True,
        preserve_possessives=True,
        preserve_numbers=False,
        preserve_urls=False,
        preserve_emails=False,
        filter_tokens=True
    )
    
    
    test_text = "I'm going to John's house at 3:30 PM. Email me at test@example.com or visit https://example.com. How are you?"

    print("\n모든 패턴 보존 + 토큰 필터링:")
    print(f"before: {test_text}")
    tokens = tokenizer.tokenize(test_text)
    print(f"after: {tokens}")

test_configurable_tokenizer()

모든 패턴 보존 + 토큰 필터링:
before: I'm going to John's house at 3:30 PM. Email me at test@example.com or visit https://example.com. How are you?
after: ["I'm", 'going', 'to', "John's", 'house', 'at', 'PM', '.', 'Email', 'me', 'at', 'test', 'example', '.', 'com', 'or', 'visit', 'https', 'example', '.', 'com', '.', 'How', 'are', 'you', '?']

In [3]:
# tokenizer comparison
test_text = "I'm going to John's house at 3:30 PM. Email me at test@example.com or visit https://example.com. How are you?"
nltk.word_tokenize(test_text),WhitespaceTokenizer().tokenize(test_text)

(['I',
  "'m",
  'going',
  'to',
  'John',
  "'s",
  'house',
  'at',
  '3:30',
  'PM',
  '.',
  'Email',
  'me',
  'at',
  'test',
  '@',
  'example.com',
  'or',
  'visit',
  'https',
  ':',
  '//example.com',
  '.',
  'How',
  'are',
  'you',
  '?'],
 ["I'm",
  'going',
  'to',
  "John's",
  'house',
  'at',
  '3:30',
  'PM.',
  'Email',
  'me',
  'at',
  'test@example.com',
  'or',
  'visit',
  'https://example.com.',
  'How',
  'are',
  'you?'])

## preprocessor class

In [4]:
# sample
preprocessor = Preprocessor(type='test', tokenizer_type='custom') # tokenize
text = "I'm going to John's house at 3:30 PM. Email me at test@example.com or visit https://example.com. How are you?"

sentences = preprocessor.split_sentences(text)
for sentence in sentences:
    #print(preprocessor.tokenize_sentence(sentence))
    print(preprocessor.split_word_pos(preprocessor.tokenize_sentence(sentence)))

(["I'm", 'going', 'to', "John's", 'house', 'at', 'PM', '.'], ['NNP', 'VBG', 'TO', 'NNP', 'NN', 'IN', 'NNP', '.'])
(['Email', 'me', 'at', 'test', 'example', '.', 'com', 'or', 'visit', 'https', 'example', '.', 'com', '.'], ['VB', 'PRP', 'IN', 'NN', 'NN', '.', 'NN', 'CC', 'NN', 'JJ', 'NN', '.', 'NN', '.'])
(['How', 'are', 'you', '?'], ['WRB', 'VBP', 'PRP', '.'])

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/bagjuhyeon/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/bagjuhyeon/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /Users/bagjuhyeon/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

예상하는 json 데이터 구조
<br>
~~~json
{
  "text": "원본 텍스트",
  "tokens": ["토큰1", "토큰2"],
  "pos_tags": ["NN", "VB"],
  "metadata": {
    "source": "수능",
    "year": "2023",
    "month": "6",
    "note": ".",
    "gender": "M",
    "type": "listening"
  }
}
~~~

## 수능 Corpus 전처리

In [10]:
# 파일 경로 확인.
proj_path = os.path.dirname(os.path.dirname(Path.cwd()))
corpora_dir = os.path.join(proj_path, 'Corpora')
listening_article_path = os.path.join(corpora_dir, 'CSAT_raw', 'csat_listening_article.xlsx')
reading_article_path = os.path.join(corpora_dir, 'CSAT_raw', 'csat_reading_article.xlsx')
textbook_article_path = os.path.join(corpora_dir, 'CSAT_raw', 'english_textbook_article.xlsx')

# 파일 경로 유효성 확인.
if not os.path.exists(listening_article_path):
    raise FileNotFoundError(f"Listening article file not found at {listening_article_path}")
if not os.path.exists(reading_article_path):
    raise FileNotFoundError(f"Reading article file not found at {reading_article_path}")
if not os.path.exists(textbook_article_path):
    raise FileNotFoundError(f"Textbook article file not found at {textbook_article_path}")
print("All file paths are valid.")

All file paths are valid.

In [11]:
# 영어 듣기 지문 읽어오기
listening_article = pd.read_excel(listening_article_path)
listening_article

,년도,월,번호,출처,본문,비고
0,2016.0,11,1.0,수능,"W: Charlie, where did you get these apples? Th...",.
1,NaN,NaN,2.0,NaN,M: Excuse me. I see the 2 o’clock flight to Da...,.
2,NaN,NaN,3.0,NaN,"W: Hello, listeners! This is One Minute Health...",.
3,NaN,NaN,4.0,NaN,"M: Ms. Robinson, what was your opinion of Mr. ...",.
4,NaN,NaN,5.0,NaN,"W: How was everything, Mr. Silverman? \nM: Goo...",.
...,...,...,...,...,...,...
1302,NaN,NaN,13.0,NaN,① W: What can I do for you today?\nM: I'd like...,그림의 상황에 적절한 대화를 고르는 문제 / 답 4
1303,NaN,NaN,14.0,NaN,W: You must be my new next door neighbor. Welc...,NaN
1304,NaN,NaN,15.0,NaN,"W: Hey, Joe. How are you doing?\nM: Hi, Michel...",NaN
1305,NaN,NaN,16.0,NaN,"W: Peter, how's the planning for the school fe...",NaN
1306,NaN,NaN,17.0,NaN,W: Steve heard Nancy Brown on a radio show. Sh...,NaN

In [9]:
listening_article.loc[0,'본문']

'W: Charlie, where did you get these apples? They look so fresh! M: My grandpa sent them from his farm. He sent me quite a lot. W: Wow, I envy you. They look so delicious. Can I have one? M: Sure. Take as many as you want.'

In [17]:
# 전체 행은 1307, 본문이 있는 행은 1234 -> 본문이 있는 행만 기준으로 처리
listening_article.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1307 entries, 0 to 1306
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   년도      77 non-null     float64
 1   월       77 non-null     object
 2   번호      1306 non-null   float64
 3   출처      77 non-null     object
 4   본문      1234 non-null   object
 5   비고      1291 non-null   object
dtypes: float64(2), object(4)
memory usage: 61.4+ KB

In [18]:
# 결측치 제거 후 불필요 행 지우기
preprocessor = Preprocessor(type='test', tokenizer_type='custom') # tokenize
listening_article = preprocessor.fillter_values(listening_article).dropna(how='any')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/bagjuhyeon/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/bagjuhyeon/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /Users/bagjuhyeon/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
데이터 형식 통일 중..: 100%|██████████| 1307/1307 [00:00<00:00, 2883.25it/s]

In [20]:
listening_article

,년도,월,번호,출처,본문,비고
0,2016.0,11,1.0,수능,"W: Charlie, where did you get these apples? Th...",.
1,2016.0,11,2.0,수능,M: Excuse me. I see the 2 o’clock flight to Da...,.
2,2016.0,11,3.0,수능,"W: Hello, listeners! This is One Minute Health...",.
3,2016.0,11,4.0,수능,"M: Ms. Robinson, what was your opinion of Mr. ...",.
4,2016.0,11,5.0,수능,"W: How was everything, Mr. Silverman? \nM: Goo...",.
...,...,...,...,...,...,...
1286,1999.0,11,14.0,수능,"Woman: Hi, John. How are you? \nMan : Not very...",.
1287,1999.0,11,15.0,수능,"Man : Hi, Su-mi, congratulations! I heard on t...",.
1288,1999.0,11,16.0,수능,"Today, Id like to talk about the future of edu...",.
1289,1999.0,11,17.0,수능,Man : Suppose you are leaving on a long trip t...,.
1302,2003.0,9,13.0,모의,① W: What can I do for you today?\nM: I'd like...,그림의 상황에 적절한 대화를 고르는 문제 / 답 4

In [21]:
listening_article = preprocessor.change_data_type(listening_article)

/var/folders/3t/7cyq0j713bn7qcyfypl8dx3w0000gn/T/ipykernel_83831/1232950257.py:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corpus['년도'] = corpus['년도'].astype('int')
/var/folders/3t/7cyq0j713bn7qcyfypl8dx3w0000gn/T/ipykernel_83831/1232950257.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corpus['월'] = corpus['월'].astype('int')
/var/folders/3t/7cyq0j713bn7qcyfypl8dx3w0000gn/T/ipykernel_83831/1232950257.py:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corpus['번호'] = corpus['번호'].astype('int')

In [22]:
listening_article.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1218 entries, 0 to 1302
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   년도      1218 non-null   object
 1   월       1218 non-null   object
 2   번호      1218 non-null   object
 3   출처      1218 non-null   object
 4   본문      1218 non-null   object
 5   비고      1218 non-null   object
dtypes: object(6)
memory usage: 66.6+ KB

In [528]:
print(listening_article['출처'].unique())
print(listening_article['년도'].unique())
print(listening_article['월'].unique())
print(listening_article['번호'].unique())
print(listening_article['비고'].unique())

['수능' '모의']
['2016' '2017' '2018' '2019' '2020' '2021' '2022' '2023' '2024' '2015'
 '2025' '2014' '2013' '2012' '2011' '2010' '2009' '2008' '2007' '2006'
 '2005' '2004' '2003' '2002' '2001' '2000' '1999']
['11' '12' '6' '9']
['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14' '15' '16'
 '17' '18' '19' '20' '21']
['.' '그림의 상황에 적절한 대화를 고르는 문제 / 답 4' '그림의 상황에 적절한 대화를 고르는 문제 / 답 3'
 '그림의 상황에 적절한 대화를 고르는 문제 / 답 5' '그림의 상황에 적절한 대화를 고르는 문제 / 답 1'
 '그림의 상황에 적절한 대화를 고르는 문제 / 답 2' 'A5' 'A7' 'A16' 'A17' 'A19' 'A20']

병렬 처리 참고: https://yganalyst.github.io/data_handling/memo_17_parallel/

In [18]:
def preprocess_article(corpus: pd.DataFrame, corpus_type: str, preprocessor: Preprocessor, json_handler: JsonFileHandler, save_path: str):
    
    if not os.path.exists(save_path):
        raise FileNotFoundError(f"Save path not found at {save_path}")

    allowed_expression = r"[^a-zA-Z,.']" # 허용된 문자열 패턴

    if 'test' in corpus_type: # 수능 corpus
        for idx, row in tqdm(corpus.iterrows(), desc='separating sentences..', total=len(corpus)):
            sentences = preprocessor.split_sentences(row['본문'])
            # clear
            before_gender = 'N' # 초기 화자의 성별 초기화
            for sentence in sentences:  # 문장 더미에서 하나의 문장을 가져와서
                
                current_gender = preprocessor.get_gender(sentence)   # 문장 내 화자 성별 정보 추출
                if current_gender == 'N':   # 만약 문장 내에서 확인이 되지 않는다면,
                    current_gender = before_gender # 이전 화자의 성별 유지
                else:   # 문장 내에세 화자 성별이 포착되었다면,
                    before_gender = current_gender # 다음 문장을 위해 성별 정보 업데이트
                
                if current_gender != 'N':
                    sentence = sentence.replace(current_gender+':', '') # 원 문장에서 성별 정보 제거
                    sentence = sentence.replace(current_gender+' ', '') # 원 문장에서 성별 정보 제거

                cleaned_sentence = sentence.lower()
                #cleaned_sentence = contractions.fix(cleaned_sentence) 축약형 풀지 않는 것으로 변경
                cleaned_sentence = re.sub(allowed_expression, ' ', cleaned_sentence) # 여러 spacebar가 포함되지만, tokenize에서 정리됨. 영어, 콤마, 온점, 퍼센트만 유지
                
                tokenized = preprocessor.tokenize_sentence(cleaned_sentence) # 문장 -> 어절 분리
                word_list, pos_list = preprocessor.split_word_pos(tokenized) # 어절 -> 단어 및 품사 분리

                metadata = {
                    "source": row['출처'],
                    "year": row['년도'],
                    "month": row['월'],
                    "note": row['비고'],
                    "gender": current_gender,
                    "type": corpus_type
                }
                
                # 여기서 문제네,,idx 는 외부 루프라, 한 cell 안 문장에 대해 동일 id 발급하니, overwrite됨.
                #json_data = preprocessor.generate_json_data(id = idx, text=sentence, tokens=word_list, pos_tags=pos_list, metadata=metadata)
                json_file_name = f"{corpus_type}_article_{row['년도']}_{row['출처']}.json"
                json_file_path = os.path.join(save_path, json_file_name)

                # 그렇다면 여기서 먼저 파일이 있는지 체크하고, 있다면 length를 먼저 가져와서 해야겠네,,
                if os.path.exists(json_file_path):
                    with open(json_file_path, 'r', encoding='utf-8') as f:
                        existing_data = json.load(f)
                    id = len(existing_data)
                else:
                    id = 0

                json_data = preprocessor.generate_json_data(id = id+1, text=sentence, tokens=word_list, pos_tags=pos_list, metadata=metadata)
                json_handler.update_json_file(json_file_path, json_data)
    
    elif corpus_type == 'textbook':
        for idx, row in tqdm(corpus.iterrows(), desc='separating sentences..', total=len(corpus)):
            sentences = preprocessor.split_sentences(row['본문'])

            for sentence in sentences:  # 문장 더미에서 하나의 문장을 가져와서
                cleaned_sentence = sentence.lower()
                #cleaned_sentence = contractions.fix(cleaned_sentence)
                cleaned_sentence = re.sub(allowed_expression, ' ', cleaned_sentence) # 여러 spacebar가 포함되지만, tokenize에서 정리됨. 영어, 콤마, 온점, 퍼센트만 유지
                
                tokenized = preprocessor.tokenize_sentence(cleaned_sentence) # 문장 -> 어절 분리
                word_list, pos_list = preprocessor.split_word_pos(tokenized) # 어절 -> 단어 및 품사 분리

                metadata = {
                    "source": row['출처'],
                    "note": row['비고'],
                    "type": corpus_type
                }
                
                json_data = preprocessor.generate_json_data(id = idx, text=sentence, tokens=word_list, pos_tags=pos_list, metadata=metadata)
                json_file_name = f"{corpus_type}_article_{row['출처']}.json"
                json_file_path = os.path.join(save_path, json_file_name)

                # 그렇다면 여기서 먼저 파일이 있는지 체크하고, 있다면 length를 먼저 가져와서 해야겠네,,
                if os.path.exists(json_file_path):
                    with open(json_file_path, 'r', encoding='utf-8') as f:
                        existing_data = json.load(f)
                    id = len(existing_data)
                else:
                    id = 0

                json_data = preprocessor.generate_json_data(id = id+1, text=sentence, tokens=word_list, pos_tags=pos_list, metadata=metadata)
                json_handler.update_json_file(json_file_path, json_data)
    else:
        raise ValueError(f"Invalid corpus type: {corpus_type}")

### 바로 실행,,

In [13]:
save_path = os.path.join(corpora_dir, 'CSAT-latest')
save_path

'/Users/bagjuhyeon/Documents/WorkSpace/corpus-comparison/Corpora/CSAT-latest'

In [19]:
preprocessor = Preprocessor(type='test', tokenizer_type='custom')
json_handler = JsonFileHandler()

# 영어 듣기 지문 읽어오기
listening_article = pd.read_excel(listening_article_path)
listening_article = preprocessor.fillter_values(listening_article).dropna(how='any')
listening_article = preprocessor.change_data_type(listening_article)
preprocess_article(corpus=listening_article, corpus_type='test_listening', preprocessor=preprocessor, json_handler=json_handler, save_path=save_path)

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/bagjuhyeon/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/bagjuhyeon/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /Users/bagjuhyeon/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
데이터 형식 통일 중..: 100%|██████████| 1307/1307 [00:00<00:00, 2879.31it/s]
separating sentences..: 100%|██████████| 1218/1218 [02:07<00:00,  9.59it/s]

### 읽기 지문도 동일하게 처리

In [20]:
# 영어 듣기 지문 읽어오기
reading_article = pd.read_excel(reading_article_path)
reading_article = preprocessor.fillter_values(reading_article).dropna(how='any')
reading_article = preprocessor.change_data_type(reading_article)
preprocess_article(corpus=reading_article, corpus_type='test_reading', preprocessor=preprocessor, json_handler=json_handler, save_path=save_path)

데이터 형식 통일 중..: 100%|██████████| 2553/2553 [00:00<00:00, 2710.83it/s]
separating sentences..: 100%|██████████| 2168/2168 [01:54<00:00, 19.01it/s]

## 영어 교과서 Corpus 전처리

예상하는 json 데이터 구조
<br>
~~~json
{
  "text": "원본 텍스트",
  "tokens": ["토큰1", "토큰2"],
  "pos_tags": ["NN", "VB"],
  "metadata": {
    "source": "수능",
    "year": "2023",
    "month": "6",
    "note": ".",
    "gender": "M",
    "type": "listening"
  }
}
~~~

In [21]:
textbook_article = pd.read_excel(textbook_article_path)
textbook_article.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 698 entries, 0 to 697
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   출판사     698 non-null    object
 1   저자      698 non-null    object
 2   과정      698 non-null    object
 3   교과서     698 non-null    object
 4   단원      698 non-null    object
 5   단원명     695 non-null    object
 6   본문제목    643 non-null    object
 7   본문      644 non-null    object
 8   비고      698 non-null    object
dtypes: object(9)
memory usage: 49.2+ KB

In [46]:
save_path

'/Users/bagjuhyeon/Documents/WorkSpace/corpus-comparison/Corpora/CSAT-latest'

In [22]:
preprocessor = Preprocessor(type='textbook', tokenizer_type='custom')
json_handler = JsonFileHandler()
textbook_article = preprocessor.fillter_values(textbook_article).dropna(how='any')
textbook_article = preprocessor.change_data_type(textbook_article)
preprocess_article(corpus=textbook_article, corpus_type='textbook', preprocessor=preprocessor, json_handler=json_handler, save_path=save_path)

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/bagjuhyeon/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/bagjuhyeon/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /Users/bagjuhyeon/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
데이터 형식 통일 중..: 100%|██████████| 698/698 [00:00<00:00, 7185.75it/s]
separating sentences..: 100%|██████████| 644/644 [02:30<00:00,  4.28it/s]

# Corpus 분석

## 수능 및 모의고사 지문 분석

아래에서는 단순히 CSAT, textbook만 합쳤는데, HAL이나 SUBTLEX랑도 여기서 다시 합쳐서 POS 기준으로 존재하지 않는 단어 뺄 필요가 있겠네,,

축약어 풀기는 진행하지 x. 축약어 같은 것들이 infomality를 나타내는 중요한 지표로 쓰일 수도 있다고 하고, 다른 비교 대상 copora에서도 풀지 않았음.

### **어간 추출(Stemming) 및 표제어 추출(Lemmatization)**
- 두 기법 모두 자연어 처리에서 텍스트 전처리 과정 중에 단어의 원형을 찾는 데 사용.

- 일반적으로 표제어 추출은 어간 추출보다 정교하고 문맥을 잘 이해하는 방식이기 때문에, 자연어 처리에서 더 많이 사용.<br><br>

- **어간 추출** : 단순한 접미사 제거 방식으로 단어의 어간을 추출. 결과는 사전에 있는 단어가 아닐 수 있다.

- **표제어 추출** : 문법적, 의미적으로 올바른 표준 형태의 단어를 추출. 결과는 사전에 등재된 실제 단어.<br><br>

1. **어간 추출 (Stemming)** : 

    - 어간 추출은 단어의 어간(stem)만 남기고 접사(suffix)를 제거하여 단어의 기본 형태를 찾는 과정.

    - 예를 들어, "running", "runs", "runner"는 모두 "run"이라는 어간을 가지고 있다. 따라서 어간 추출은 이들을 모두 "run"으로 축소.

    - 어간 추출은 단순히 규칙 기반의 접미사 제거 방식이기 때문에, 결과로 나오는 단어는 실제 사전에 있는 단어일 필요는 없고, 때로는 일반적이지 않은 형태일 수 있다.<br><br>


2. **표제어 추출 (Lemmatization)** :

    - 표제어 추출은 단어의 표준 형태인 표제어(lemma)를 찾는 과정입니다.

    - 표제어는 사전에 등재된 실제 단어. 예를 들어, "running"의 표제어는 "run", "better"의 표제어는 "good"입니다.

    - 표제어 추출은 단어의 문맥을 고려하고, 형태소 분석(morphological analysis)을 수행하여 단어의 형태와 문법적 의미를 이해한 후에 추출.

    - 따라서 표제어 추출은 언어적, 문법적 규칙을 적용하여 단어를 정규화하는 과정.

### **고민해 봐야할 점**
- **위 두 과정이 필요한가?**

    - 일단 비교 대상이 COCA라면, COCA랑 뭘 비교할 수 있을지 생각해보자.

    - 현재 전처리에서는 동사의 품사 변형 형들에 대한 고려가 되어 있지 않음.
        - e.g. 'running' -> 'VBG' not a 'Verb'
        - 이를 lemmatation 해야할까? 아니면, wordPiece 사용해서 'preprocessing' -> 'pre#' + 'process' + '#ing' 처럼 처리해서 동사별 비교 때 동사의 범위로 봐야할까?
        
    - 축약형들에 대한 조금 더 나은 처리 방법
        - e.g. 'I'm' -> 'I am'으로 잘 되지만, 'Car's' -> 'car s'로 분리된다. 모호하거나 "'s" 에 대한 처리가 조금 더 필요할 듯,,